# Generated by Django 5.2.6 on 2025-09-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='deleted_at',
        ),
    ]
